//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TextDemo1Entities : DbContext
    {
        public TextDemo1Entities()
            : base("name=TextDemo1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DengLus> DengLus { get; set; }
        public virtual DbSet<NewsInfoes> NewsInfoes { get; set; }
        public virtual DbSet<UserDengLus> UserDengLus { get; set; }
        public virtual DbSet<UserLoads> UserLoads { get; set; }
    
        public virtual ObjectResult<P_ShowPageDate_Result> P_ShowPageDate(Nullable<int> pageindex, Nullable<int> pageSize, ObjectParameter total)
        {
            var pageindexParameter = pageindex.HasValue ?
                new ObjectParameter("pageindex", pageindex) :
                new ObjectParameter("pageindex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_ShowPageDate_Result>("P_ShowPageDate", pageindexParameter, pageSizeParameter, total);
        }
    }
}
