//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCUI显示层.web.webservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewsInfoes", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class NewsInfoes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NTitleField;
        
        private System.Nullable<System.DateTime> NDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nid {
            get {
                return this.NidField;
            }
            set {
                if ((this.NidField.Equals(value) != true)) {
                    this.NidField = value;
                    this.RaisePropertyChanged("Nid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NTitle {
            get {
                return this.NTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.NTitleField, value) != true)) {
                    this.NTitleField = value;
                    this.RaisePropertyChanged("NTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> NDate {
            get {
                return this.NDateField;
            }
            set {
                if ((this.NDateField.Equals(value) != true)) {
                    this.NDateField = value;
                    this.RaisePropertyChanged("NDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NContent {
            get {
                return this.NContentField;
            }
            set {
                if ((object.ReferenceEquals(this.NContentField, value) != true)) {
                    this.NContentField = value;
                    this.RaisePropertyChanged("NContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="web.webservice.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVCUI显示层.web.webservice.HelloWorldResponse HelloWorld(MVCUI显示层.web.webservice.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.HelloWorldResponse> HelloWorldAsync(MVCUI显示层.web.webservice.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 webServiceGetAllMVCListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceGetAllMVCList", ReplyAction="*")]
        MVCUI显示层.web.webservice.webServiceGetAllMVCListResponse webServiceGetAllMVCList(MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceGetAllMVCList", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListResponse> webServiceGetAllMVCListAsync(MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceGetAllMVCListByName", ReplyAction="*")]
        MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponse webServiceGetAllMVCListByName(MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceGetAllMVCListByName", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponse> webServiceGetAllMVCListByNameAsync(MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 webServiceGetAllMVCListByIdResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceGetAllMVCListById", ReplyAction="*")]
        MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponse webServiceGetAllMVCListById(MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceGetAllMVCListById", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponse> webServiceGetAllMVCListByIdAsync(MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ni 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceeditNews", ReplyAction="*")]
        MVCUI显示层.web.webservice.webServiceeditNewsResponse webServiceeditNews(MVCUI显示层.web.webservice.webServiceeditNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceeditNews", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceeditNewsResponse> webServiceeditNewsAsync(MVCUI显示层.web.webservice.webServiceeditNewsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ni 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceDeleteNews", ReplyAction="*")]
        MVCUI显示层.web.webservice.webServiceDeleteNewsResponse webServiceDeleteNews(MVCUI显示层.web.webservice.webServiceDeleteNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceDeleteNews", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceDeleteNewsResponse> webServiceDeleteNewsAsync(MVCUI显示层.web.webservice.webServiceDeleteNewsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ni 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceAddNews", ReplyAction="*")]
        MVCUI显示层.web.webservice.webServiceAddNewsResponse webServiceAddNews(MVCUI显示层.web.webservice.webServiceAddNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/webServiceAddNews", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceAddNewsResponse> webServiceAddNewsAsync(MVCUI显示层.web.webservice.webServiceAddNewsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVCUI显示层.web.webservice.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVCUI显示层.web.webservice.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceGetAllMVCListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceGetAllMVCList", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceGetAllMVCListRequestBody Body;
        
        public webServiceGetAllMVCListRequest() {
        }
        
        public webServiceGetAllMVCListRequest(MVCUI显示层.web.webservice.webServiceGetAllMVCListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class webServiceGetAllMVCListRequestBody {
        
        public webServiceGetAllMVCListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceGetAllMVCListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceGetAllMVCListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceGetAllMVCListResponseBody Body;
        
        public webServiceGetAllMVCListResponse() {
        }
        
        public webServiceGetAllMVCListResponse(MVCUI显示层.web.webservice.webServiceGetAllMVCListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceGetAllMVCListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCUI显示层.web.webservice.NewsInfoes[] webServiceGetAllMVCListResult;
        
        public webServiceGetAllMVCListResponseBody() {
        }
        
        public webServiceGetAllMVCListResponseBody(MVCUI显示层.web.webservice.NewsInfoes[] webServiceGetAllMVCListResult) {
            this.webServiceGetAllMVCListResult = webServiceGetAllMVCListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceGetAllMVCListByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceGetAllMVCListByName", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequestBody Body;
        
        public webServiceGetAllMVCListByNameRequest() {
        }
        
        public webServiceGetAllMVCListByNameRequest(MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceGetAllMVCListByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public webServiceGetAllMVCListByNameRequestBody() {
        }
        
        public webServiceGetAllMVCListByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceGetAllMVCListByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceGetAllMVCListByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponseBody Body;
        
        public webServiceGetAllMVCListByNameResponse() {
        }
        
        public webServiceGetAllMVCListByNameResponse(MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceGetAllMVCListByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCUI显示层.web.webservice.NewsInfoes[] webServiceGetAllMVCListByNameResult;
        
        public webServiceGetAllMVCListByNameResponseBody() {
        }
        
        public webServiceGetAllMVCListByNameResponseBody(MVCUI显示层.web.webservice.NewsInfoes[] webServiceGetAllMVCListByNameResult) {
            this.webServiceGetAllMVCListByNameResult = webServiceGetAllMVCListByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceGetAllMVCListByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceGetAllMVCListById", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequestBody Body;
        
        public webServiceGetAllMVCListByIdRequest() {
        }
        
        public webServiceGetAllMVCListByIdRequest(MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceGetAllMVCListByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public webServiceGetAllMVCListByIdRequestBody() {
        }
        
        public webServiceGetAllMVCListByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceGetAllMVCListByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceGetAllMVCListByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponseBody Body;
        
        public webServiceGetAllMVCListByIdResponse() {
        }
        
        public webServiceGetAllMVCListByIdResponse(MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceGetAllMVCListByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCUI显示层.web.webservice.NewsInfoes webServiceGetAllMVCListByIdResult;
        
        public webServiceGetAllMVCListByIdResponseBody() {
        }
        
        public webServiceGetAllMVCListByIdResponseBody(MVCUI显示层.web.webservice.NewsInfoes webServiceGetAllMVCListByIdResult) {
            this.webServiceGetAllMVCListByIdResult = webServiceGetAllMVCListByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceeditNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceeditNews", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceeditNewsRequestBody Body;
        
        public webServiceeditNewsRequest() {
        }
        
        public webServiceeditNewsRequest(MVCUI显示层.web.webservice.webServiceeditNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceeditNewsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCUI显示层.web.webservice.NewsInfoes ni;
        
        public webServiceeditNewsRequestBody() {
        }
        
        public webServiceeditNewsRequestBody(MVCUI显示层.web.webservice.NewsInfoes ni) {
            this.ni = ni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceeditNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceeditNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceeditNewsResponseBody Body;
        
        public webServiceeditNewsResponse() {
        }
        
        public webServiceeditNewsResponse(MVCUI显示层.web.webservice.webServiceeditNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceeditNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool webServiceeditNewsResult;
        
        public webServiceeditNewsResponseBody() {
        }
        
        public webServiceeditNewsResponseBody(bool webServiceeditNewsResult) {
            this.webServiceeditNewsResult = webServiceeditNewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceDeleteNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceDeleteNews", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceDeleteNewsRequestBody Body;
        
        public webServiceDeleteNewsRequest() {
        }
        
        public webServiceDeleteNewsRequest(MVCUI显示层.web.webservice.webServiceDeleteNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceDeleteNewsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCUI显示层.web.webservice.NewsInfoes ni;
        
        public webServiceDeleteNewsRequestBody() {
        }
        
        public webServiceDeleteNewsRequestBody(MVCUI显示层.web.webservice.NewsInfoes ni) {
            this.ni = ni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceDeleteNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceDeleteNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceDeleteNewsResponseBody Body;
        
        public webServiceDeleteNewsResponse() {
        }
        
        public webServiceDeleteNewsResponse(MVCUI显示层.web.webservice.webServiceDeleteNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceDeleteNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool webServiceDeleteNewsResult;
        
        public webServiceDeleteNewsResponseBody() {
        }
        
        public webServiceDeleteNewsResponseBody(bool webServiceDeleteNewsResult) {
            this.webServiceDeleteNewsResult = webServiceDeleteNewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceAddNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceAddNews", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceAddNewsRequestBody Body;
        
        public webServiceAddNewsRequest() {
        }
        
        public webServiceAddNewsRequest(MVCUI显示层.web.webservice.webServiceAddNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceAddNewsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCUI显示层.web.webservice.NewsInfoes ni;
        
        public webServiceAddNewsRequestBody() {
        }
        
        public webServiceAddNewsRequestBody(MVCUI显示层.web.webservice.NewsInfoes ni) {
            this.ni = ni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class webServiceAddNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="webServiceAddNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCUI显示层.web.webservice.webServiceAddNewsResponseBody Body;
        
        public webServiceAddNewsResponse() {
        }
        
        public webServiceAddNewsResponse(MVCUI显示层.web.webservice.webServiceAddNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class webServiceAddNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool webServiceAddNewsResult;
        
        public webServiceAddNewsResponseBody() {
        }
        
        public webServiceAddNewsResponseBody(bool webServiceAddNewsResult) {
            this.webServiceAddNewsResult = webServiceAddNewsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MVCUI显示层.web.webservice.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MVCUI显示层.web.webservice.WebServiceSoap>, MVCUI显示层.web.webservice.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.HelloWorldResponse MVCUI显示层.web.webservice.WebServiceSoap.HelloWorld(MVCUI显示层.web.webservice.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVCUI显示层.web.webservice.HelloWorldRequest inValue = new MVCUI显示层.web.webservice.HelloWorldRequest();
            inValue.Body = new MVCUI显示层.web.webservice.HelloWorldRequestBody();
            MVCUI显示层.web.webservice.HelloWorldResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.HelloWorldResponse> MVCUI显示层.web.webservice.WebServiceSoap.HelloWorldAsync(MVCUI显示层.web.webservice.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.HelloWorldResponse> HelloWorldAsync() {
            MVCUI显示层.web.webservice.HelloWorldRequest inValue = new MVCUI显示层.web.webservice.HelloWorldRequest();
            inValue.Body = new MVCUI显示层.web.webservice.HelloWorldRequestBody();
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.webServiceGetAllMVCListResponse MVCUI显示层.web.webservice.WebServiceSoap.webServiceGetAllMVCList(MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest request) {
            return base.Channel.webServiceGetAllMVCList(request);
        }
        
        public MVCUI显示层.web.webservice.NewsInfoes[] webServiceGetAllMVCList() {
            MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest inValue = new MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceGetAllMVCListRequestBody();
            MVCUI显示层.web.webservice.webServiceGetAllMVCListResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceGetAllMVCList(inValue);
            return retVal.Body.webServiceGetAllMVCListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListResponse> MVCUI显示层.web.webservice.WebServiceSoap.webServiceGetAllMVCListAsync(MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest request) {
            return base.Channel.webServiceGetAllMVCListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListResponse> webServiceGetAllMVCListAsync() {
            MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest inValue = new MVCUI显示层.web.webservice.webServiceGetAllMVCListRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceGetAllMVCListRequestBody();
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceGetAllMVCListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponse MVCUI显示层.web.webservice.WebServiceSoap.webServiceGetAllMVCListByName(MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest request) {
            return base.Channel.webServiceGetAllMVCListByName(request);
        }
        
        public MVCUI显示层.web.webservice.NewsInfoes[] webServiceGetAllMVCListByName(string name) {
            MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest inValue = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequestBody();
            inValue.Body.name = name;
            MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceGetAllMVCListByName(inValue);
            return retVal.Body.webServiceGetAllMVCListByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponse> MVCUI显示层.web.webservice.WebServiceSoap.webServiceGetAllMVCListByNameAsync(MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest request) {
            return base.Channel.webServiceGetAllMVCListByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameResponse> webServiceGetAllMVCListByNameAsync(string name) {
            MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest inValue = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByNameRequestBody();
            inValue.Body.name = name;
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceGetAllMVCListByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponse MVCUI显示层.web.webservice.WebServiceSoap.webServiceGetAllMVCListById(MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest request) {
            return base.Channel.webServiceGetAllMVCListById(request);
        }
        
        public MVCUI显示层.web.webservice.NewsInfoes webServiceGetAllMVCListById(int id) {
            MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest inValue = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequestBody();
            inValue.Body.id = id;
            MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceGetAllMVCListById(inValue);
            return retVal.Body.webServiceGetAllMVCListByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponse> MVCUI显示层.web.webservice.WebServiceSoap.webServiceGetAllMVCListByIdAsync(MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest request) {
            return base.Channel.webServiceGetAllMVCListByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdResponse> webServiceGetAllMVCListByIdAsync(int id) {
            MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest inValue = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceGetAllMVCListByIdRequestBody();
            inValue.Body.id = id;
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceGetAllMVCListByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.webServiceeditNewsResponse MVCUI显示层.web.webservice.WebServiceSoap.webServiceeditNews(MVCUI显示层.web.webservice.webServiceeditNewsRequest request) {
            return base.Channel.webServiceeditNews(request);
        }
        
        public bool webServiceeditNews(MVCUI显示层.web.webservice.NewsInfoes ni) {
            MVCUI显示层.web.webservice.webServiceeditNewsRequest inValue = new MVCUI显示层.web.webservice.webServiceeditNewsRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceeditNewsRequestBody();
            inValue.Body.ni = ni;
            MVCUI显示层.web.webservice.webServiceeditNewsResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceeditNews(inValue);
            return retVal.Body.webServiceeditNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceeditNewsResponse> MVCUI显示层.web.webservice.WebServiceSoap.webServiceeditNewsAsync(MVCUI显示层.web.webservice.webServiceeditNewsRequest request) {
            return base.Channel.webServiceeditNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceeditNewsResponse> webServiceeditNewsAsync(MVCUI显示层.web.webservice.NewsInfoes ni) {
            MVCUI显示层.web.webservice.webServiceeditNewsRequest inValue = new MVCUI显示层.web.webservice.webServiceeditNewsRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceeditNewsRequestBody();
            inValue.Body.ni = ni;
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceeditNewsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.webServiceDeleteNewsResponse MVCUI显示层.web.webservice.WebServiceSoap.webServiceDeleteNews(MVCUI显示层.web.webservice.webServiceDeleteNewsRequest request) {
            return base.Channel.webServiceDeleteNews(request);
        }
        
        public bool webServiceDeleteNews(MVCUI显示层.web.webservice.NewsInfoes ni) {
            MVCUI显示层.web.webservice.webServiceDeleteNewsRequest inValue = new MVCUI显示层.web.webservice.webServiceDeleteNewsRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceDeleteNewsRequestBody();
            inValue.Body.ni = ni;
            MVCUI显示层.web.webservice.webServiceDeleteNewsResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceDeleteNews(inValue);
            return retVal.Body.webServiceDeleteNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceDeleteNewsResponse> MVCUI显示层.web.webservice.WebServiceSoap.webServiceDeleteNewsAsync(MVCUI显示层.web.webservice.webServiceDeleteNewsRequest request) {
            return base.Channel.webServiceDeleteNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceDeleteNewsResponse> webServiceDeleteNewsAsync(MVCUI显示层.web.webservice.NewsInfoes ni) {
            MVCUI显示层.web.webservice.webServiceDeleteNewsRequest inValue = new MVCUI显示层.web.webservice.webServiceDeleteNewsRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceDeleteNewsRequestBody();
            inValue.Body.ni = ni;
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceDeleteNewsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCUI显示层.web.webservice.webServiceAddNewsResponse MVCUI显示层.web.webservice.WebServiceSoap.webServiceAddNews(MVCUI显示层.web.webservice.webServiceAddNewsRequest request) {
            return base.Channel.webServiceAddNews(request);
        }
        
        public bool webServiceAddNews(MVCUI显示层.web.webservice.NewsInfoes ni) {
            MVCUI显示层.web.webservice.webServiceAddNewsRequest inValue = new MVCUI显示层.web.webservice.webServiceAddNewsRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceAddNewsRequestBody();
            inValue.Body.ni = ni;
            MVCUI显示层.web.webservice.webServiceAddNewsResponse retVal = ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceAddNews(inValue);
            return retVal.Body.webServiceAddNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceAddNewsResponse> MVCUI显示层.web.webservice.WebServiceSoap.webServiceAddNewsAsync(MVCUI显示层.web.webservice.webServiceAddNewsRequest request) {
            return base.Channel.webServiceAddNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCUI显示层.web.webservice.webServiceAddNewsResponse> webServiceAddNewsAsync(MVCUI显示层.web.webservice.NewsInfoes ni) {
            MVCUI显示层.web.webservice.webServiceAddNewsRequest inValue = new MVCUI显示层.web.webservice.webServiceAddNewsRequest();
            inValue.Body = new MVCUI显示层.web.webservice.webServiceAddNewsRequestBody();
            inValue.Body.ni = ni;
            return ((MVCUI显示层.web.webservice.WebServiceSoap)(this)).webServiceAddNewsAsync(inValue);
        }
    }
}
